SQLALCHEMY_DATABASE_URI = f'sqlite:///database.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS = False
WTF_CSRF_SECRET_KEY = 'asdasdas12312313-3-3--33_#_#_!@#(!@^$%()/=1'

CSRF_ENABLED = True
SECRET_KEY = 'asdas!@#!@#!@#!__)U*^&#^&#)#_#$*DSKJSkjdskajd152348172315243'
RECAPTCHA_USE_SSL = False
RECAPTCHA_PUBLIC_KEY = '6LdTKMUUAAAAALr5IK0TY7WyCl4sL_oWdLd0iK0I'
RECAPTCHA_PRIVATE_KEY = '6LdTKMUUAAAAAHCBoS0KjIkE87A7BhKDok7RxxpU'
